--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/newlandpe/LanguageManager
build-by-default: true
branches:
- main
projects:
  LanguageManager:
    path: ""
    libs:
      - src: newlandpe/libLanguage/libLanguage
        version: ^0.0.1
